language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAJ7KOXQAEVDUSHZDA
  secret_access_key:
    secure: ON80Jgy+Phl+v7vf3aNGm/l82lxJPdRfXy6yv19o23ez54nfTqRHf1LF9K5P3p7NnsnIBtJun2dRGmJjxFmpoPKCjx1kUBCGaRVFUxeUqurMpEn7fNnj790iRlsYsHBoXkj12HpxmIVEfB6nqtNxz4BqmTu8nFtwSIzQ8LudqlaQpGkML/xpfu0BklEd91hg1XmAhwsgErf5UxiQwVU7b1mnfJ9i6OVtN3T5vkUe+Fo1MOsv71yRoxF9caz9NYOrioOsngMthWHRJdHJyxu1TtVJUTcFPbku43dobzEpfddoPqealLMh6zfKOV+UtArpEOc5hPGZ6cesnk2LxFXDNugixDv8hh0bK8ZqAivSRBS77Obtdk+524T9BjbFj3uVvGg1iDW6cevfGzWmZwegHCNmL+ofiVZ26G+TDjZhEY16dCynsM8cbBVIU7pfcGTfbPTT/1utWHSIDv0S5LA2/nRd12G3d9v3hrwqL2h/Fv27TwaH0dfKivnJ4UZVy4cSk4HpB5FAJ98uT0BucZ6Yr4bw82TQjykvMLLLgkEroNApujjisUodX6TW5/1j/8jjjphBXjfz5QAg7LsRpaNwZ0nIBLUkFXxR96Bo88wNt55GsmzILaL2y5L/+8Q5Eyzb9HYHOBVpgnzGejsFPd2XGGM//FdalTgXROftiFjuWgA=
  bucket: portfolio-tim
  acl: ''
  on:
    repo: dreamchasersuon/portfolio
