language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: portfolio-tim
  acl: public_read
  region: us-east-1
env:
  global:
  - secure: JLuAcrGFgvdoqWhbCZVwrzUTgtmQvRRN5Gfbg+l4Kb7AP/13z/qL++PzzZPEoJAOrx1vqi6SS+BA74Nh83zhaubZLtt5i6UwDr+xMvESy/SYuGZuLuj1baRiXXoUMPCvVwuRqvLih/wL+o4K6Fst9hxbHZQS/In0dfETuknM4uzXdMoUPBF12RZgIvmVM87PbViza2zOmREEGzdukxNZ5eso7hMF1f63XzYXJJYvBxSbF0FOwKiaairzYRUzWs4WP7dNkJBJfLxWKlFYAyJ4Dnndbmzdav32/tDxDB5jErfFGGgQOSasurWyNJJ3CkHUxYRIzLFuWoadVjxrrCTb+C0tn4UMIZ/0G0Gd6Kxi4MFqZH7YpJ4LxH3W942gDPNKwiVGqFPy+tWztmu7E6V5BnVIblterwPwJ058H/CzLNsErm8TdznOfQQCPqGsKIlSuVAlsAEYeGfYzAeAA6H1mGicxe6bAPtL8HkKubOunnY5cbFFYZ6Zrbjn2jt/N80zJBrlQVuv+2o9XVv/In3XYdzZ0CJmzUG1f6OG6Qqs3FbDFx1zQQz1aVQJ1pDGeks2xVxgTnBOhzgB11DTIQuF1jsId+L5+R4rhuQcbmwz6GoKSqRkYB9HxMZUZ6ttugKi6yZnfeVSXPLLoQQ5ltodfzFHEQtgkiPW2vuBKqTVuy4=
  - secure: syp0BjK85uGfjUl5hcLD0XF1qYPyKvu4BrcRkYgaZCmKlfe67BXWc7mElyYNp+J0c/SpVMaGAyl99kJ6uYt+m7i+XK+eSam4+yWaPoN4vxSUc8WbHVVmUv64tv/xIaa8ZdpxJg0oYv9NaVM6VoJQRxejLxveItvVE/gt5sUR3xmlo/m44nnHTkpogIt1YQGCrtP2F/DVdCyhrj5yCGL0vkm+UevcNmgWJCH97CEfNjLPkg1tMNHcbwURKXxSv7/HkYvmCyUeKeIUV8Kwpb2LxGS5u0KX2K540J9hl33heq6MxhOR6F1bYfiKt+3QRs+8jdaNZgKjebtjxVLnSBf1pi+CecsSE62NDcni079BGiiseKXOJYjNbiP32r8oWDOPleDW7ijRrFFsc0CjCyYTN2SGxcOcDyHy2L++F7VqDRZKwL4lZhnkj7/+GCzVOTQt2f5GjjlBsacuewgbSqjJeWIYXwlM/Ex0Wl/fN07ivBmCfpwI4L0S0CMHurW5nEXhiIgFVziaIR2JeH4MLyiXbY9qmaDlPRU8MsQdNllxWw5hYWiKa7ihDj7LTYDHqE5KqGqLANfpXFwBVWbUj2xg14MHoa0aGQuX7nr4oBvDpcWtDpIY/ttGhKsIbMsdCwudFmO6iOxGQagJ85/g+blreAHiRPSvyvCIVwU68HY1CAU=
