sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "10.0"
branches:
  only:
    - master
script:
  - yarn install
  - yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
