language: node.js
node.js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn install
- yarn build
- yarn deploy
deploy:
  provider: s3
  access_key_id: AKIAIX4EZQLMAEHQUC6A
  secret_access_key:
    secure: 1yqtWdVO1vRd6ZYmBUxYYvddLqAvUkemhmJmMmS8je3SyH3SML9NDVEsRrzXbmMWjE67CrdQBFtZaxNQh3XiHerSjqgPifwIMbpABX/LFVeLpUDvxBl7lNp3EcLg4Qf3yRIf8u2BJbHjccrYgmnToao/SkJNpPtpJp0tiVPkva9ZDqVoU+8qkqPCPjaRW1m8HWQSk8D+4sE62WV/LmWOdcwREciRf58P3nLmUDVZQ/UgM6GLFo/VYLg/81tbdyHgcj113dM3K/gHlT6Ph1IeIaZBC7C0jr/INnXmTYSCWTluwo4c7Gi+OM7gMXiaHdM2j5vY8UnTze6E4UnXpnmSJ3FnnoJ3KbO1P7e9IksNE3R+YDBB/AyMCfJi+kVmY7myerBO2PkYJyquKbF0azAtkJttbe1qLvzOsp0zyknvMusvfCkDuUfVelEBu1MSGS5WTj1gtfbEBcad+UDkPMoLJPeVtwu0OW2KAlJf8Kfw5IY1lKlZ8/2nqY+rkGC4b6TfATWuBRmMIGc2nQlO8NKC31PQDinNEBDhbcZdl6kVafma0Jjos/pyrq9p9Rcm29jrnXw8I7BAuDpfqJLaZEJF1KIh2uPmvGkU62ImlNbDEQ+IP5DmzWoW2W15YeSqyQHHcWZrabLSFpAO3W6PPlR2XFSpQ7/MIDAuL39qUvllfq4=
  bucket: s3://portfolio-tim
