language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync build/ s3://portfolio-tim --region=us-east-2 --delete
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  acl: public_read
  skip_cleanup: true
  on:
    branch: master
