language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAIX4EZQLMAEHQUC6A
  secret_access_key:
    secure: AWAckny7UQ6s9DKjqzWuCtE6a7YLgQtCDK9FgAHcmMHhgInkarrrjM8t9G4e8wSWWUb57wZQoTdyb4a0zo1MJUazUOqWUsz4fXstMZnGrBMhhu9JThqv60sJftG1qJvNews0qH/hwiuKP9W53lN5sCpIVQxVfiGgVFQax+o5F8FajL0XMrIyFeuR2JzAgCu4+UPW6ubuvPuEfIWpwBlwtoz9MqMx/3+lmyA5ZS9Fc0GA1HqyFvbKoDdR2q2ytQr9oeNpKBmZJIyNYLq7AwX5DTvbCw6V4yN2kf5E4McDEloCesTVBs8JRrbfbJg3WBFPd3CDYP2CCUFa0W1+K6ltRqcRB4Jj/q0pr8/pPk14Cs8roHDNNqBRNRrbaET2lMRVUfJ+p3UmGhy2hmRVy7l38xVcp5kSvy52NENh/8aAqnVJENiZ0GfLR5+NreTBtxNYkXtQP5D/FP33gcc6ykbqoaJxR5xmJrY7D8z09DPdSSEQgs5EmbtEQWboTDcmJWwX1bVjxyWWWDy5/cpko96x+w9WNfQkjbAgDsZ8QEA8aAvf/EqEfmLl9pG863P3jU0Zr2k/czMIv1LRmen6XIpH55NxrV7wxbEtQPyDj5bDkUybGpmsu2RxzQIgXICD8GmRED7wHAzheh1Dr/1bEK0ZLp1IgiwIiIRrDJB9+biRDY4=
  bucket: portfolio-tim
  acl: public_read_write
  on:
    repo: dreamchasersuon/portfolio
