language: node_js
node_js:
- node
cache:
- yarn
install:
- yarn install
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAJ7KOXQAEVDUSHZDA
  secret_access_key:
    secure: 3ynzuRfmjnPwoAp5NE1QPtk+eAVqvrc1lKwY6wee0eJinLK0QBO3XMowASXJKoevEQgJ+ijDnnC57jHzns4x21dBmiZq0JJKn0as8GhaTHTjv6evEDi6qdF5i0rFmLXkPqmnVcnWQWJp6G1s6ts38tESW/tWeSVZp4DJTnxPicQrvJBL+6wwnXTvtScHjV+AJzS1BEa/hb+cfsTyhuqFJYNa4cUlyi1oOZ6n18yfwjNbXXrcbszaC8UTUtWaWdEAjw6Xsr3xb+XY2MLitoWusb9wO9ZVpvjf0df/JF6TC63GnL1heufh3Zzo+YfU6WuotXUDMMnO20FGeIb2FlXjSy2HsXRYaqkPV+0lJ2CR9Q1DwzQgWkDRS5TYYoAgN17lOMZ+ebhoN5u1yGrJtfvADT7j6QPv3/8/ZnS7fMbOePJoKws9CTmqA9hACVg46TeliHIzMJuhk8HbZ4nYGrAbJ0DJ9pVp4OgLQjjAT/T1ZQ8emDQ5IOpof86k+Rha0J1IfuS29Ma3h0AuMKUDnLOB3yTPbNweiZEJt/9cuRwBV3t0EM8+tybV0wPVPnjBRgdsaC0WU7LbLGjANZHzYNqDeIhcX0wBhNj5zUiRhTeCGvMDDiUZH99bJE8i7gXN4kmxTY+r9QpcHMADxtI9ONf/ZUoDOTiBMyG9INKUFYadvPk=
  bucket: portfolio-tim
  acl: public_read
  on:
    repo: dreamchasersuon/portfolio
