language: node.js
node.js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn build
- yarn deploy
deploy:
  provider: s3
  access_key_id: AKIAIX4EZQLMAEHQUC6A
  secret_access_key:
    secure: jOv9hpfzHfEYjYJdMjIZjDL5QEOFW4/CyKW2z+F4Na4wIjWtgaWH9yOnZurIcP8aYTA7FrbEUU0CW/lykIjQC3BshqVxa833fLgCAxCTeLEs1gmUhbh1fJDc0FB/SPEk68NS8pUoUWzwfaVfbHHeajlz4AAHkw9yecMHgfFGcM4m2dHPqEaPn6zXsKe2kuZcHW/yvq4X0MYu8FxDisnyoyR9mUJKtY5VYxJw2IL96NPCKIMciIGmf4lZiN0D4aLm+/HQ1f2zf1bsLWaSAswPXmOboPnZcl/OCDSZOi+KD/sLZ7tZ0wLUQmfQlLE0rsqGFVCbynk2JCWDoegMQOeaxhJxZaPZ3GgvfJtUMBS30m1RU8mUna33GzMi0Di2ASRWb14dYmWuS8jhfj4Y3K7Gf5EpbV/03ivOk+A4eucxRqrG453foyCMhyiPM7GiQ6rIx03ZLy5K55YdPMHQiQZ8UR+R0SzO1W23lBOqI2ZSFPHjruhnjCZBMz40wo+HPUb4rhBNAGrTCKsrFtwCiZO3AR7b8AnQoJ+LuVNGUKJ3a871hRBT2ca5tmNyuloAlyKb1w18VoSUPLp+3m9gtBvb/X6zyNPrglEaZNNQoJa+/W0L5g4bn5MZhOQGsLl4PIQExv/ZTTb9u0iaqOmiuDpc2K90sntN5kC2gyTnXoRgRnE=
  bucket: s3://portfolio-tim
